version: '3'

services:
  # Database
  mongo:
    image: mongo
    container_name: go_mongo
    ports:
      - '27017:27017'
    volumes:
      - ./db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: gomongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
